/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AguardandoRouteImport } from './routes/aguardando'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LojistaIndexRouteImport } from './routes/lojista.index'
import { Route as LojistaLoginRouteImport } from './routes/lojista.login'
import { Route as AppSuporteRouteImport } from './routes/_app.suporte'
import { Route as AppSolicitacoesRouteImport } from './routes/_app.solicitacoes'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppNotificacoesRouteImport } from './routes/_app.notificacoes'
import { Route as AppLojasRouteImport } from './routes/_app.lojas'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppFavoritosRouteImport } from './routes/_app.favoritos'
import { Route as AppDebugRouteImport } from './routes/_app.debug'
import { Route as AppBuscarRouteImport } from './routes/_app.buscar'
import { Route as AppQrIdRouteImport } from './routes/_app.qr.$id'
import { Route as AppOfertaIdRouteImport } from './routes/_app.oferta.$id'
import { Route as AppLojaIdRouteImport } from './routes/_app.loja.$id'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AguardandoRoute = AguardandoRouteImport.update({
  id: '/aguardando',
  path: '/aguardando',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LojistaIndexRoute = LojistaIndexRouteImport.update({
  id: '/lojista/',
  path: '/lojista/',
  getParentRoute: () => rootRouteImport,
} as any)
const LojistaLoginRoute = LojistaLoginRouteImport.update({
  id: '/lojista/login',
  path: '/lojista/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSuporteRoute = AppSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AppRoute,
} as any)
const AppSolicitacoesRoute = AppSolicitacoesRouteImport.update({
  id: '/solicitacoes',
  path: '/solicitacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacoesRoute = AppNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppLojasRoute = AppLojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritosRoute = AppFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AppRoute,
} as any)
const AppDebugRoute = AppDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => AppRoute,
} as any)
const AppBuscarRoute = AppBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => AppRoute,
} as any)
const AppQrIdRoute = AppQrIdRouteImport.update({
  id: '/qr/$id',
  path: '/qr/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOfertaIdRoute = AppOfertaIdRouteImport.update({
  id: '/oferta/$id',
  path: '/oferta/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppLojaIdRoute = AppLojaIdRouteImport.update({
  id: '/loja/$id',
  path: '/loja/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aguardando': typeof AguardandoRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/privacidade': typeof PrivacidadeRoute
  '/registro': typeof RegistroRoute
  '/termos': typeof TermosRoute
  '/buscar': typeof AppBuscarRoute
  '/debug': typeof AppDebugRoute
  '/favoritos': typeof AppFavoritosRoute
  '/home': typeof AppHomeRoute
  '/lojas': typeof AppLojasRoute
  '/notificacoes': typeof AppNotificacoesRoute
  '/perfil': typeof AppPerfilRoute
  '/solicitacoes': typeof AppSolicitacoesRoute
  '/suporte': typeof AppSuporteRoute
  '/lojista/login': typeof LojistaLoginRoute
  '/lojista/': typeof LojistaIndexRoute
  '/loja/$id': typeof AppLojaIdRoute
  '/oferta/$id': typeof AppOfertaIdRoute
  '/qr/$id': typeof AppQrIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aguardando': typeof AguardandoRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/privacidade': typeof PrivacidadeRoute
  '/registro': typeof RegistroRoute
  '/termos': typeof TermosRoute
  '/buscar': typeof AppBuscarRoute
  '/debug': typeof AppDebugRoute
  '/favoritos': typeof AppFavoritosRoute
  '/home': typeof AppHomeRoute
  '/lojas': typeof AppLojasRoute
  '/notificacoes': typeof AppNotificacoesRoute
  '/perfil': typeof AppPerfilRoute
  '/solicitacoes': typeof AppSolicitacoesRoute
  '/suporte': typeof AppSuporteRoute
  '/lojista/login': typeof LojistaLoginRoute
  '/lojista': typeof LojistaIndexRoute
  '/loja/$id': typeof AppLojaIdRoute
  '/oferta/$id': typeof AppOfertaIdRoute
  '/qr/$id': typeof AppQrIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/aguardando': typeof AguardandoRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/privacidade': typeof PrivacidadeRoute
  '/registro': typeof RegistroRoute
  '/termos': typeof TermosRoute
  '/_app/buscar': typeof AppBuscarRoute
  '/_app/debug': typeof AppDebugRoute
  '/_app/favoritos': typeof AppFavoritosRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/lojas': typeof AppLojasRoute
  '/_app/notificacoes': typeof AppNotificacoesRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/solicitacoes': typeof AppSolicitacoesRoute
  '/_app/suporte': typeof AppSuporteRoute
  '/lojista/login': typeof LojistaLoginRoute
  '/lojista/': typeof LojistaIndexRoute
  '/_app/loja/$id': typeof AppLojaIdRoute
  '/_app/oferta/$id': typeof AppOfertaIdRoute
  '/_app/qr/$id': typeof AppQrIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aguardando'
    | '/login'
    | '/painel'
    | '/privacidade'
    | '/registro'
    | '/termos'
    | '/buscar'
    | '/debug'
    | '/favoritos'
    | '/home'
    | '/lojas'
    | '/notificacoes'
    | '/perfil'
    | '/solicitacoes'
    | '/suporte'
    | '/lojista/login'
    | '/lojista/'
    | '/loja/$id'
    | '/oferta/$id'
    | '/qr/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aguardando'
    | '/login'
    | '/painel'
    | '/privacidade'
    | '/registro'
    | '/termos'
    | '/buscar'
    | '/debug'
    | '/favoritos'
    | '/home'
    | '/lojas'
    | '/notificacoes'
    | '/perfil'
    | '/solicitacoes'
    | '/suporte'
    | '/lojista/login'
    | '/lojista'
    | '/loja/$id'
    | '/oferta/$id'
    | '/qr/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/aguardando'
    | '/login'
    | '/painel'
    | '/privacidade'
    | '/registro'
    | '/termos'
    | '/_app/buscar'
    | '/_app/debug'
    | '/_app/favoritos'
    | '/_app/home'
    | '/_app/lojas'
    | '/_app/notificacoes'
    | '/_app/perfil'
    | '/_app/solicitacoes'
    | '/_app/suporte'
    | '/lojista/login'
    | '/lojista/'
    | '/_app/loja/$id'
    | '/_app/oferta/$id'
    | '/_app/qr/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AguardandoRoute: typeof AguardandoRoute
  LoginRoute: typeof LoginRoute
  PainelRoute: typeof PainelRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RegistroRoute: typeof RegistroRoute
  TermosRoute: typeof TermosRoute
  LojistaLoginRoute: typeof LojistaLoginRoute
  LojistaIndexRoute: typeof LojistaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aguardando': {
      id: '/aguardando'
      path: '/aguardando'
      fullPath: '/aguardando'
      preLoaderRoute: typeof AguardandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lojista/': {
      id: '/lojista/'
      path: '/lojista'
      fullPath: '/lojista/'
      preLoaderRoute: typeof LojistaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lojista/login': {
      id: '/lojista/login'
      path: '/lojista/login'
      fullPath: '/lojista/login'
      preLoaderRoute: typeof LojistaLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/suporte': {
      id: '/_app/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof AppSuporteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/solicitacoes': {
      id: '/_app/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/solicitacoes'
      preLoaderRoute: typeof AppSolicitacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notificacoes': {
      id: '/_app/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AppNotificacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lojas': {
      id: '/_app/lojas'
      path: '/lojas'
      fullPath: '/lojas'
      preLoaderRoute: typeof AppLojasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favoritos': {
      id: '/_app/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AppFavoritosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/debug': {
      id: '/_app/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof AppDebugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/buscar': {
      id: '/_app/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof AppBuscarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/qr/$id': {
      id: '/_app/qr/$id'
      path: '/qr/$id'
      fullPath: '/qr/$id'
      preLoaderRoute: typeof AppQrIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oferta/$id': {
      id: '/_app/oferta/$id'
      path: '/oferta/$id'
      fullPath: '/oferta/$id'
      preLoaderRoute: typeof AppOfertaIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loja/$id': {
      id: '/_app/loja/$id'
      path: '/loja/$id'
      fullPath: '/loja/$id'
      preLoaderRoute: typeof AppLojaIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBuscarRoute: typeof AppBuscarRoute
  AppDebugRoute: typeof AppDebugRoute
  AppFavoritosRoute: typeof AppFavoritosRoute
  AppHomeRoute: typeof AppHomeRoute
  AppLojasRoute: typeof AppLojasRoute
  AppNotificacoesRoute: typeof AppNotificacoesRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppSolicitacoesRoute: typeof AppSolicitacoesRoute
  AppSuporteRoute: typeof AppSuporteRoute
  AppLojaIdRoute: typeof AppLojaIdRoute
  AppOfertaIdRoute: typeof AppOfertaIdRoute
  AppQrIdRoute: typeof AppQrIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBuscarRoute: AppBuscarRoute,
  AppDebugRoute: AppDebugRoute,
  AppFavoritosRoute: AppFavoritosRoute,
  AppHomeRoute: AppHomeRoute,
  AppLojasRoute: AppLojasRoute,
  AppNotificacoesRoute: AppNotificacoesRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppSolicitacoesRoute: AppSolicitacoesRoute,
  AppSuporteRoute: AppSuporteRoute,
  AppLojaIdRoute: AppLojaIdRoute,
  AppOfertaIdRoute: AppOfertaIdRoute,
  AppQrIdRoute: AppQrIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AguardandoRoute: AguardandoRoute,
  LoginRoute: LoginRoute,
  PainelRoute: PainelRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RegistroRoute: RegistroRoute,
  TermosRoute: TermosRoute,
  LojistaLoginRoute: LojistaLoginRoute,
  LojistaIndexRoute: LojistaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
